source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'URLImageCache_Example', :exclusive => true do
  pod "URLImageCache", :path => "../"
end

target 'URLImageCache_Tests', :exclusive => true do
  pod "URLImageCache", :path => "../"

  
end
